# Generated by Django 3.2.3 on 2022-02-17 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220217_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=255)),
                ('salary', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
